project_id = "lbserxuqjcxmuvucokyc"

[functions.create-user]
verify_jwt = true

[functions.generate-report-pdf]
verify_jwt = true

[functions.check-overdue-books]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.process-reservation-expiry]
verify_jwt = false

[functions.register-school]
verify_jwt = false
